#!/usr/bin/zsh

dot_clean_up(){
    unset GIT_DIR
    unset GIT_WORK_TREE
    unset DOTREMOTE
    unset DOTDEST
    unset DOTGIT
    cd $OLDPWD
}

dot_success(){
    dot_clean_up
    exit 0
}

dot_fail(){
    dot_clean_up
    echo "dot failed. See traceback for more information."
    exit 1
}

# Read config from current dir
source dotrc 2> /dev/null

# Read config from $HOME/.dotrc
source $HOME/.dotrc 2> /dev/null

if [ -z "$DOTGIT" ];then
    DOTGIT=${HOME}/dotfiles.git
fi
if [ -z "$DOTDEST" ];then
    DOTDEST=$HOME
fi
if [ -z "$DOTREMOTE" ];then
    echo "You have to define the remote location of your dotfile repository."
    echo "Set DOTREMOTE or edit your ~/.dotrc."
    dot_fail
fi

subcmd="$1"
OLDCWD=`pwd`

cd $DOTDEST
dot_clear(){
    echo "This will delete all files provided by $DOTREMOTE."
    echo "Are you sure you want to continue? [yes/No]"
    read answer
    if [ "$answer" = "yes" ]; then
        dotbackup=$DOTDEST/dotfiles_BACKUP`date +%s`.tar
        ssh $DOTHOST "cd ${REMOTEDIR} && git ls-tree -r HEAD --name-only" |\
            tee | tar -cf $dotbackup --ignore-failed-read --remove-files -T -
        ret=$?
        if [ $ret -eq 0 ]; then
            rm -rf $DOTGIT
        fi
        echo "Cleared files have been backed up in $dotbackup."
        return $ret
    else
        return 0
    fi
}

dot_unclear(){
    dotbackup=`\ls -r dotfiles_BACKUP* | head -1`
    tar xf $dotbackup
    ret=$?
    if [ $ret -eq 0 ]; then
        rm $dotbackup
        echo "Reinstated files from $dotbackup."
    fi
    return $ret
}

dot_init(){
    export GIT_DIR=$DOTGIT
    export GIT_WORK_TREE=$DOTDEST
    git init
    git remote add origin $DOTREMOTE
    git checkout -b master
    git pull origin master
    git branch --set-upstream-to origin/master master
    git config status.showuntrackedfiles no
    unset GIT_DIR
    unset GIT_WORK_TREE
    return $?
}

dot_submodule_init(){
    export GIT_DIR=$DOTGIT
    export GIT_WORK_TREE=$DOTDEST
    git submodule init
    git submodule update
    unset GIT_DIR
    unset GIT_WORK_TREE
    return $?
}

if [ "$subcmd" = "clear" ]; then
    dot_clear
    if [ $? -ne 0 ]; then
        dot_fail
    fi
    dot_success
elif [ "$subcmd" = "unclear" ]; then
    dot_unclear
    if [ $? -ne 0 ]; then
        dot_fail
    fi
    dot_success
elif [ "$subcmd" = "init" ]; then
    # Clone dotfile repository into home directory
    dot_init
    if [ $? -ne 0 ]; then
        echo "Destination $DOTDEST is not clean. Run 'dot clear' first."
        dot_fail
    fi
    dot_submodule_init
    if [ $? -ne 0 ]; then
        echo "Destination $DOTDEST is not clean. Run 'dot clear' first."
        dot_fail
    fi
    dot_success
elif  [ "$subcmd" = "shell" ]; then
    GIT_DIR=$DOTGIT zsh
    dot_success
else
    # else pass all arguments to git with GIT_DIR set
    GIT_DIR=$DOTGIT git "$@"
fi
